cloudProvider: aws

awsRegion: ""

autoDiscovery:
  clusterName: ""

rbac:
  create: true

  serviceAccount:
    create: true
    name: cluster-autoscaler
    annotations: {}

extraArgs:
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  skip-nodes-with-local-storage: false

replicaCount: 1
