replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

  className: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

  hosts:
    - host: nginx.yourdomain.com
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true

  # StorageClass Configuration
  storageClass: efs-sc

  provisioningMode: efs-ap

  fileSystemId: fs-03acc169816429b30

  directoryPerms: "700"

  mountOptions:
    - tls

  reclaimPolicy: Retain

  volumeBindingMode: Immediate

  # PVC Configuration
  accessMode: ReadWriteMany

  size: 10Gi

  # Container Mount Path
  mountPath: /usr/share/nginx/html

resources: {}