# =========================================================
# POD / APPLICATION CONFIGURATION
# =========================================================

replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80

# =========================================================
# HPA CONFIGURATION
# =========================================================

hpa:
  enabled: true

  minReplicas: 1
  maxReplicas: 100

  cpu:
    enabled: true
    targetAverageUtilization: 70

  memory:
    enabled: false
    targetAverageUtilization: 80

# =========================================================
# INGRESS / ALB CONFIGURATION
# =========================================================

ingress:
  enabled: true

  className: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

# =========================================================
# PERSISTENT VOLUME CLAIM (PVC) CONFIGURATION
# =========================================================

persistence:
  enabled: false

  existingClaim: nginx-app-pvc

  accessMode: ReadWriteMany
  size: 10Gi

  mountPath: /usr/share/nginx/html

# =========================================================
# STORAGECLASS CONFIGURATION
# =========================================================

storageClass:
  name: efs-sc

  provisioner: efs.csi.aws.com

  parameters:
    provisioningMode: efs-ap
    fileSystemId: fs-03acc169816429b30
    directoryPerms: "700"

  mountOptions:
    - tls

  reclaimPolicy: Retain

  volumeBindingMode: Immediate