apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/vinoinbox1-coder/helm.git
    targetRevision: HEAD
    path: helm-charts/aws-load-balancer-controller

    helm:
      values: |
        clusterName: prod-eks-cluster
        serviceAccount:
          create: true
          name: aws-load-balancer-controller

          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::757933576142:role/aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true