apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cluster-autoscaler
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vinoinbox1-coder/helm.git 
    targetRevision: HEAD
    path: helm-charts/cluster-autoscaler

    helm:
      values: |
        awsRegion: us-west-2

        autoDiscovery:
          clusterName: prod-eks-cluster

        rbac:
          serviceAccount:
            annotations:
		eks.amazonaws.com/role-arn: arn:aws:iam::992566513680:role/cluster-autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
