apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cluster-autoscaler
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vinoinbox1-coder/helm.git
    targetRevision: HEAD
    path: helm-charts/cluster-autoscaler

    helm:
      values: |
        awsRegion: us-east-1

        cloudProvider: aws

        autoDiscovery:
          clusterName: prod-eks-cluster

        rbac:
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::757933576142:role/cluster-autoscaler

        extraArgs:
          balance-similar-node-groups: "true"
          skip-nodes-with-system-pods: "false"
          skip-nodes-with-local-storage: "false"
          expander: least-waste

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
