apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
      labels:
        app: {{ .Chart.Name }}

    spec:
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

# {{- if .Values.persistence.enabled }}
#           volumeMounts:
#             - name: efs-storage
#               mountPath: {{ .Values.persistence.mountPath }}
# {{- end }}

#           resources:
# {{ toYaml .Values.resources | indent 12 }}

# {{- if .Values.persistence.enabled }}
#       volumes:
#         - name: efs-storage
#           persistentVolumeClaim:
#             claimName: {{ .Values.persistence.existingClaim }}
# {{- end }}