apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx
spec:
  replicas: 100
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-storage
              mountPath: /mnt
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: gp3-pvc
      # serviceAccountName: s3-sa