apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-aaf91868-e3c5-48cd-ba2b-00669c71b506
  storageClassName: ""