{{- if .Values.persistence.enabled }}

apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: {{ .Values.persistence.storageClass }}

provisioner: efs.csi.aws.com

parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-03acc169816429b30
  directoryPerms: "700"

mountOptions:
  - tls

reclaimPolicy: Retain

volumeBindingMode: Immediate

{{- end }}